export type Judge0Language = {
  id: number;
  name: string;
  isArchived: boolean;
};

export const judge0Languages: Judge0Language[] = [
  { id: 45, name: "Assembly (NASM 2.14.02)", isArchived: false },
  { id: 2, name: "Bash (4.0)", isArchived: true },
  { id: 1, name: "Bash (4.4)", isArchived: true },
  { id: 46, name: "Bash (5.0.0)", isArchived: false },
  { id: 3, name: "Basic (fbc 1.05.0)", isArchived: true },
  { id: 47, name: "Basic (FBC 1.07.1)", isArchived: false },
  { id: 75, name: "C (Clang 7.0.1)", isArchived: false },
  { id: 76, name: "C++ (Clang 7.0.1)", isArchived: false },
  { id: 15, name: "C++ (g++ 4.8.5)", isArchived: true },
  { id: 14, name: "C++ (g++ 4.9.4)", isArchived: true },
  { id: 13, name: "C++ (g++ 5.4.0)", isArchived: true },
  { id: 12, name: "C++ (g++ 6.3.0)", isArchived: true },
  { id: 11, name: "C++ (g++ 6.4.0)", isArchived: true },
  { id: 10, name: "C++ (g++ 7.2.0)", isArchived: true },
  { id: 9, name: "C (gcc 4.8.5)", isArchived: true },
  { id: 8, name: "C (gcc 4.9.4)", isArchived: true },
  { id: 7, name: "C (gcc 5.4.0)", isArchived: true },
  { id: 6, name: "C (gcc 6.3.0)", isArchived: true },
  { id: 5, name: "C (gcc 6.4.0)", isArchived: true },
  { id: 4, name: "C (gcc 7.2.0)", isArchived: true },
  { id: 48, name: "C (GCC 7.4.0)", isArchived: false },
  { id: 52, name: "C++ (GCC 7.4.0)", isArchived: false },
  { id: 49, name: "C (GCC 8.3.0)", isArchived: false },
  { id: 53, name: "C++ (GCC 8.3.0)", isArchived: false },
  { id: 50, name: "C (GCC 9.2.0)", isArchived: false },
  { id: 54, name: "C++ (GCC 9.2.0)", isArchived: false },
  { id: 86, name: "Clojure (1.10.1)", isArchived: false },
  { id: 18, name: "Clojure (1.8.0)", isArchived: true },
  { id: 17, name: "C# (mono 5.2.0.224)", isArchived: true },
  { id: 16, name: "C# (mono 5.4.0.167)", isArchived: true },
  { id: 51, name: "C# (Mono 6.6.0.161)", isArchived: false },
  { id: 77, name: "COBOL (GnuCOBOL 2.2)", isArchived: false },
  { id: 55, name: "Common Lisp (SBCL 2.0.0)", isArchived: false },
  { id: 19, name: "Crystal (0.23.1)", isArchived: true },
  { id: 56, name: "D (DMD 2.089.1)", isArchived: false },
  { id: 20, name: "Elixir (1.5.1)", isArchived: true },
  { id: 57, name: "Elixir (1.9.4)", isArchived: false },
  { id: 21, name: "Erlang (OTP 20.0)", isArchived: true },
  { id: 58, name: "Erlang (OTP 22.2)", isArchived: false },
  { id: 44, name: "Executable", isArchived: false },
  { id: 87, name: "F# (.NET Core SDK 3.1.202)", isArchived: false },
  { id: 59, name: "Fortran (GFortran 9.2.0)", isArchived: false },
  { id: 60, name: "Go (1.13.5)", isArchived: false },
  { id: 22, name: "Go (1.9)", isArchived: true },
  { id: 88, name: "Groovy (3.0.3)", isArchived: false },
  { id: 24, name: "Haskell (ghc 8.0.2)", isArchived: true },
  { id: 23, name: "Haskell (ghc 8.2.1)", isArchived: true },
  { id: 61, name: "Haskell (GHC 8.8.1)", isArchived: false },
  { id: 25, name: "Insect (5.0.0)", isArchived: true },
  { id: 62, name: "Java (OpenJDK 13.0.1)", isArchived: false },
  { id: 28, name: "Java (OpenJDK 7)", isArchived: true },
  { id: 27, name: "Java (OpenJDK 8)", isArchived: true },
  { id: 26, name: "Java (OpenJDK 9 with Eclipse OpenJ9)", isArchived: true },
  { id: 63, name: "JavaScript (Node.js 12.14.0)", isArchived: false },
  { id: 30, name: "JavaScript (nodejs 7.10.1)", isArchived: true },
  { id: 29, name: "JavaScript (nodejs 8.5.0)", isArchived: true },
  { id: 78, name: "Kotlin (1.3.70)", isArchived: false },
  { id: 64, name: "Lua (5.3.5)", isArchived: false },
  { id: 89, name: "Multi-file program", isArchived: false },
  { id: 79, name: "Objective-C (Clang 7.0.1)", isArchived: false },
  { id: 31, name: "OCaml (4.05.0)", isArchived: true },
  { id: 65, name: "OCaml (4.09.0)", isArchived: false },
  { id: 32, name: "Octave (4.2.0)", isArchived: true },
  { id: 66, name: "Octave (5.1.0)", isArchived: false },
  { id: 33, name: "Pascal (fpc 3.0.0)", isArchived: true },
  { id: 67, name: "Pascal (FPC 3.0.4)", isArchived: false },
  { id: 85, name: "Perl (5.28.1)", isArchived: false },
  { id: 68, name: "PHP (7.4.1)", isArchived: false },
  { id: 43, name: "Plain Text", isArchived: false },
  { id: 69, name: "Prolog (GNU Prolog 1.4.5)", isArchived: false },
  { id: 37, name: "Python (2.6.9)", isArchived: true },
  { id: 70, name: "Python (2.7.17)", isArchived: false },
  { id: 36, name: "Python (2.7.9)", isArchived: true },
  { id: 35, name: "Python (3.5.3)", isArchived: true },
  { id: 34, name: "Python (3.6.0)", isArchived: true },
  { id: 71, name: "Python (3.8.1)", isArchived: false },
  { id: 80, name: "R (4.0.0)", isArchived: false },
  { id: 41, name: "Ruby (2.1.9)", isArchived: true },
  { id: 40, name: "Ruby (2.2.6)", isArchived: true },
  { id: 39, name: "Ruby (2.3.3)", isArchived: true },
  { id: 38, name: "Ruby (2.4.0)", isArchived: true },
  { id: 72, name: "Ruby (2.7.0)", isArchived: false },
  { id: 42, name: "Rust (1.20.0)", isArchived: true },
  { id: 73, name: "Rust (1.40.0)", isArchived: false },
  { id: 81, name: "Scala (2.13.2)", isArchived: false },
  { id: 82, name: "SQL (SQLite 3.27.2)", isArchived: false },
  { id: 83, name: "Swift (5.2.3)", isArchived: false },
  { id: 74, name: "TypeScript (3.7.4)", isArchived: false },
  { id: 84, name: "Visual Basic.Net (vbnc 0.0.0.5943)", isArchived: false },
];
